# Haven Crowdfunding Platform - Working Render Blueprint
# Two Repository Setup: Frontend + Backend
# Place this file as: haven-frontend/render.yaml

# Enable preview environments for testing changes
previews:
  generation: automatic

# NO database defined - use your existing database
# Your existing DATABASE_URL will be available through the crowdfunding environment group

# Service definitions for both repositories
services:
  # FastAPI Backend Service (from backend repository)
  - type: web
    name: haven-backend
    runtime: python
    repo: https://github.com/sudhindra-a700/haven-backend.git
    branch: main
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      # Port for the service
      - key: PORT
        value: 8000
      # Reference your existing environment group with all secrets including DATABASE_URL
      - fromGroup: crowdfunding
    
  # Streamlit Frontend Service (from frontend repository)
  - type: web
    name: haven-frontend
    runtime: python
    repo: https://github.com/sudhindra-a700/haven-frontend.git
    branch: main
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    healthCheckPath: /_stcore/health
    autoDeploy: true
    envVars:
      # Port for the service
      - key: PORT
        value: 8501
      # Reference your existing environment group with all secrets including DATABASE_URL
      - fromGroup: crowdfunding

