[global]
developmentMode = false

[server]
port = 8501
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[theme]
primaryColor = "#4caf50"
backgroundColor = "#e8f5e8"
secondaryBackgroundColor = "#c8e6c9"
textColor = "#1b5e20"
font = "sans serif"

[client]
caching = true
displayEnabled = true
showErrorDetails = false

