# Streamlit Secrets Configuration
# Note: For Render deployment, use environment variables instead
# This file is for local development only

[general]
# Backend URL (use environment variable BACKEND_URL in production)
backend_url = "http://localhost:8000"

[oauth]
# OAuth credentials (use environment variables in production)
# GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, etc.
google_client_id = ""
google_client_secret = ""
facebook_app_id = ""
facebook_app_secret = ""

[features]
# Feature flags (use environment variables in production)
translation_enabled = true
simplification_enabled = true
oauth_enabled = true

# Note: In production on Render, these values come from environment variables
# Streamlit automatically maps environment variables to st.secrets

